services:
  n8n:
    image: docker.n8n.io/n8nio/n8n:latest
    container_name: n8n
    restart: unless-stopped

    ports:
      - "5678:5678"

    environment:
      - TZ=America/Sao_Paulo
      - N8N_SECURE_COOKIE=false
      - N8N_HOST=submerge-harmonics-headlamp.ngrok-free.dev
      - N8N_PROTOCOL=https
      - WEBHOOK_URL=https://submerge-harmonics-headlamp.ngrok-free.dev/

    volumes:
      - n8n_data:/home/node/.n8n

    depends_on:
      - postgres

  postgres:
    image: postgres:16
    container_name: suba-postgres
    restart: unless-stopped

    environment:
      - POSTGRES_USER=suba
      - POSTGRES_PASSWORD=suba_dev_password
      - POSTGRES_DB=suba_db

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  n8n_data:
    external: true
    name: n8n_n8n_data
  postgres_data:


